name: Our automated terraform build

on: [push]

jobs:
  deploy-bucket:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Terraform plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.0


    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
   